### ISSUE TITLE
[FEATURE] 기본정보 CRUD api 구현

### ISSUE THREAD

**Issue by KimChanJin97** [kookmin-sw/capstone-2024-18#10]
## 제목
기본정보 CRUD api 구현

### 파트
- [ ] FE
- [x] BE
- [ ] AI

### TODO
- [x] 회원가입 시, 회원 정보뿐만 아니라 기본 정보도 빈 문자열로 저장되어야 합니다. (Member POST 요청과 BasicInfo POST 요청이 함께 발생)
- [x] 사용자가 기본 정보를 조회할 수 있어야 합니다. (GET)
- [x] 사용자가 기본 정보를 수정할 수 있어야 합니다. (PUT)

### 참고 할만한 자료
none

### 예상 작업시간(선택)
1일
