### ISSUE TITLE
[FEATURE] BasicInfoPage 구현

### ISSUE THREAD

**Issue by nanana3679** [kookmin-sw/capstone-2024-18#15]
## 제목
BasicInfoPage 구현

### 파트
- FE

### TODO
- 컴포넌트 구현
  - [x] Title
    - Props: { childres: string, onPress: () => void }
    - width: 100%, height: 고정
  - [x] CustomSlider
    - Props: { values: strings[] (선택 가능한 값들), setValue: () => void }
    - width: values.length에 상대적, height: 고정
  - [x] CustomProgressBar
    - Props: { progress: number(진행도를 나타내는 0 이상 1 이하의 수) }
    - width: 100%, height: 고정

- 페이지 구현
  - [x] 닉네임 설정
  - [x] 성별 선택
  - [x] 나이대 선택
  - [x] 지역 선택
  - [x] 선택 내용 확인

- UX
  - [x] 입력이 valid하면 버튼을 활성화하고 onPress 이벤트 발생시 다음 페이지로 이동
  - [x] Back 버튼 클릭시 이전 페이지로 이동
  - [x] 슬라이더 디자인 개선
  - [x] 하단 UI 요소 위치 고정
  - [x] 페이지와 API 연동

- API 구현
  - [x] GET http://localhost:8080/members/basic-info
  - [x] POST http://localhost:8080/members/basic-info

### 작업 브랜치
- feat/create-basic-info-screen (예정)

### 예상 작업시간(선택)
- 1~2일

### 스크린샷
![image](https://github.com/kookmin-sw/capstone-2024-18/assets/38131725/ef684b40-bc00-4c50-a78b-994dd4614d58)

![image](https://github.com/kookmin-sw/capstone-2024-18/assets/38131725/d8146674-b28c-4359-8870-c69cd7d6d5f6)

![image](https://github.com/kookmin-sw/capstone-2024-18/assets/38131725/d9e980fc-9791-44cb-9f9c-5295c8812116)

![image](https://github.com/kookmin-sw/capstone-2024-18/assets/38131725/efe42f1a-a151-44b7-a8c5-6a3a82c2b23e)

![image](https://github.com/kookmin-sw/capstone-2024-18/assets/38131725/efe42f1a-a151-44b7-a8c5-6a3a82c2b23e)

![image](https://github.com/kookmin-sw/capstone-2024-18/assets/38131725/1256160c-3494-4c20-aa4e-342a77ae35e9)
