### ISSUE TITLE
[FEATURE] 자동 페이지 전환 구현

### ISSUE THREAD

**Issue by nanana3679** [kookmin-sw/capstone-2024-18#16]
## 제목
자동 페이지 전환 구현

### 파트
- FE

### TODO
- [x] 엑세스토큰을 로컬 스토리지에 저장하도록 수정
- '/' 경로를 위한 Home 페이지 구현
  - [x] 엑세스 토큰, 리프레시 토큰, basicInfo 검사 후 '/login' 또는 '/main' 또는 '/basic-info' 으로 이동 
- [x] 원활한 테스트를 위해 '/main' 페이지에 로그아웃 버튼 구현 
- [x] 에러 핸들링

### 예상 작업시간(선택)
1일
