### ISSUE TITLE
[FEATURE] 사진 찍기, 갤러리에서 사진 가져오기 기능

### ISSUE THREAD

**Issue by gee2450** [kookmin-sw/capstone-2024-18#20]
## 제목
사진 찍기, 갤러리에서 사진 가져오기 기능

### 파트
- FE

### TODO
react-native-image-picker 사용

- [x] 카메라 촬영, 사진 가져오기 선택 모달
  - 아직 디자인 안 나와서 단순 버튼을 클릭하면 해당 함수 실행하게 구현
  - 필수 Props : { visible: boolean(모달 가시성 설정), onClose: () => void(모달 닫는 기능의 함수 전달) } 
  - 선택 Props : { setResult?: (url: string) => void (사진을 찍거나 가져올 때 사진을 따로 사용해야할 경우, 함수 설정) }
- [x] 사진 찍기 기능
  - Props : { setResult?: (uri: string) => void }
    - setResult : 찍은 이미지 임시 저장한 파일을 사용하는 함수
- [x] 갤러리에서 사진 가져오기 기능
  - Props : { setResult?: (uri: string) => void }
    - setResult : 갤러리에서 선택한 이미지 파일을 사용하는 함수 
- [x] 안드로이드 사용자의 sdk 버전에 맞는 권한 확인과 권한 요청

**Comment by nanana3679** [comment]
setResult 말고 setImageUrl은 어떨까요?

**Comment by gee2450** [comment]
좋습니다. 이름 바꿀께요
