### ISSUE TITLE
[FEATURE] 채팅 페이지 구현

### ISSUE THREAD

**Issue by nanana3679** [kookmin-sw/capstone-2024-18#31]
### 파트
- FE

### TODO
- [ ] 채팅 조건부 렌더링
  - 사용자가 sender일 경우 오른쪽, 아닐 경우 왼쪽에 보임
  - 이전 채팅과 timestamp(분), sender가 같은 경우 이전 채팅과 이어짐
  - 이어진 채팅의 첫 채팅이면 프로필, 닉네임 보임
  - 이어진 채팅의 마지막 채팅이면 timestamp 보임
  - 날짜 변경 시 표시선 보임
- [ ] 최상단 스크롤 시 서버에 이전 채팅 기록 요청
- [ ] 백그라운드 전환 또는 앱 종료시 로컬 캐시에 채팅 내역 저장
- [ ] 렌더링 최적화
- [ ] 원하는 채팅 위치로 스크롤 이동
  - 채팅 위치 계산하는 함수 정의
  - 최신 채팅이 많을 경우 맨 아래로 이동하는 버튼 제공
  - 채팅방 입장 시 마지막으로 읽었던 채팅 위치로 이동
