### ISSUE TITLE
[FEATURE] Docker 개발/테스트 compose 파일

### ISSUE THREAD

**Issue by imjanghyeok** [kookmin-sw/capstone-2024-18#4]
## 제목
Docker-compose.yml 개발/테스트 용도 설정 파일

### 파트
- [ ] FE
- [*] BE
- [ ] AI

### TODO
- [ ] Docker-compose.yml 파일 생성
- [ ] Docker-compose.yml 파일 민감한 정보 감추기
- [ ] Redis, Postgresql, Spring 3개의 컨테이너 생성 후 테스트

### 참고 할만한 자료
[https://velog.io/@jinyeong-afk/Springboot-DockerFile-docker-compose를-통한-도커-컨테이너-배포외부-접근-허용-with-Gradle](https://velog.io/@jinyeong-afk/Springboot-DockerFile-docker-compose%EB%A5%BC-%ED%86%B5%ED%95%9C-%EB%8F%84%EC%BB%A4-%EC%BB%A8%ED%85%8C%EC%9D%B4%EB%84%88-%EB%B0%B0%ED%8F%AC%EC%99%B8%EB%B6%80-%EC%A0%91%EA%B7%BC-%ED%97%88%EC%9A%A9-with-Gradle)
