### ISSUE TITLE
[FEATURE] 채팅 부가기능

### ISSUE THREAD

**Issue by imjanghyeok** [kookmin-sw/capstone-2024-18#56]
### 파트
- [x] BE

### TODO
- [x] 메시지 기록 페이지네이션
- [x] 채팅방 입장 정보 관리 
- [x] 애플리케이션 구동 정보 관리
- [x] 소켓 연결을 안했을 때 오는 메시지 관리
