### ISSUE TITLE
[FEATURE] Chip을 이용한 선택지 component 구현

### ISSUE THREAD

**Issue by gee2450** [kookmin-sw/capstone-2024-18#7]
## 제목
Chip을 이용한 선택지 component 구현

### 파트
- [x] FE
- [ ] BE
- [ ] AI

### 구현해야하는 component 이미지
![image](https://github.com/kookmin-sw/capstone-2024-18/assets/65989738/f65b9b14-62ee-41be-9239-c345d55781c4)

### TODO
- [x] 텍스트를 감싸는 선택지 구현
- [x] 텍스트를 감싸지 않고, 특정 크기(width, height)를 가지는 선택지 구현
- [x] 선택했을 때, style이 변하는 기능 구현
- [x] 선택한 선택지만 볼 수 있는 변수 설정
- [x] style 추가 입력 가능하게 코딩
- [x] 예시 코드 작성
- [ ] 올바른 이름 정하기(현재 : SelectableCategory)

### 사용 branch
feat/category-component

### 참고 할만한 자료
https://callstack.github.io/react-native-paper/docs/components/Chip/
